name: Scrape jobs

permissions: write-all

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "9 */4 * * 1,2,3,4,5"

env:
  # jq_greenhouse: "[.departments[]|{id:.jobs[].id,title:.jobs[].title,updated_at:.jobs[].updated_at,location:.jobs[].location,absolute_url:.jobs[].absolute_url,department:.name}]|sort_by(.id)"
  jq_greenhouse: "[.departments[].jobs[]|{id:.id,title,location,absolute_url}]|sort_by(.id)"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Install htmlq
        uses: baptiste0928/cargo-install@v1
        with:
          crate: htmlq
      - name: Scrape jobs
        run: |-
          curl --silent  https://api.greenhouse.io/v1/boards/alchemy/embed/departments | jq -r "$jq_greenhouse" > alchemy.json
          curl --silent  https://api.greenhouse.io/v1/boards/fastly/embed/departments | jq -r "$jq_greenhouse" > fastly.json
          curl --silent  https://api.greenhouse.io/v1/boards/figma/embed/departments | jq -r "$jq_greenhouse" > figma.json
          curl --silent  https://api.greenhouse.io/v1/boards/planetscale/embed/departments | jq -r "$jq_greenhouse" > planetscale.json
          curl --silent  https://api.greenhouse.io/v1/boards/stripe/embed/departments | jq -r "$jq_greenhouse" > stripe.json
          curl --silent  https://api.greenhouse.io/v1/boards/vercel/embed/departments | jq -r "$jq_greenhouse" > vercel.json
          curl --silent  https://api.greenhouse.io/v1/boards/github/embed/departments | jq -r "$jq_greenhouse" > github.json
          curl --silent  https://api.greenhouse.io/v1/boards/supabase/embed/departments | jq -r "$jq_greenhouse" > supabase.json
          curl --silent  https://api.greenhouse.io/v1/boards/datadog/embed/departments | jq -r "$jq_greenhouse" > datadog.json
          curl --silent  https://api.greenhouse.io/v1/boards/consensys/embed/departments | jq -r "$jq_greenhouse" > consensys.json
          curl --silent  https://api.greenhouse.io/v1/boards/cloudflare/embed/departments | jq -r "$jq_greenhouse" > cloudflare.json
          curl --silent  https://api.greenhouse.io/v1/boards/sentry/embed/departments | jq -r "$jq_greenhouse" > sentry.json
          curl --silent "https://www.shopify.com/careers?search%5Bkeywords%5D=&search%5Bteams%5D%5B%5D=engineering" | htmlq --attribute href a | grep /careers/ > shopify.txt
          curl --silent "https://careers.squareup.com/us/en/jobs" | htmlq --attribute href a | grep https://www.smartrecruiters.com/Square/ > square.txt
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
