name: Scrape jobs

permissions: write-all

on:
  push:
  workflow_dispatch:
    schedule:
      - cron: "9 * * * 1,2,3,4,5"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install htmlq
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: htmlq
      - name: Fetch latest data
        run: |-
          curl https://api.greenhouse.io/v1/boards/alchemy/embed/departments | jq . > alchemy.json
          curl https://api.greenhouse.io/v1/boards/fastly/embed/departments | jq . > fastly.json
          curl https://api.greenhouse.io/v1/boards/figma/embed/departments | jq . > figma.json
          curl https://api.greenhouse.io/v1/boards/planetscale/embed/departments | jq . > planetscale.json
          curl https://api.greenhouse.io/v1/boards/stripe/embed/departments | jq . > stripe.json
          curl https://api.greenhouse.io/v1/boards/vercel/embed/departments | jq . > vercel.json
          curl https://www.shopify.com/careers?search%5Bkeywords%5D=&search%5Bteams%5D%5B%5D=engineering | htmlq . > shopify.html

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
